### ISSUE TITLE
Possible integration with django-jinja

### ISSUE THREAD

**Issue by niwinz** [MoritzS/jinja2-django-tags#1]
Hi!

I'm a django-jinja developer and maintainer. 

First of all, great work. I thinking that it make sense join forces and integrate that into django-jinja directly. If you are interested we can talk how we can colaborate.

Making this extensions easy available for all versions of django, not only django 1.8.

That do you thing about?

**Comment by MoritzS** [comment]
Yeah, sure!

**Comment by strig** [comment]
Do it! The {% load %} tag is breaking django-debug-toolbar for me. It would be great to have it included in django-jinja.

**Comment by MoritzS** [comment]
This library doesn't include the `{% load %}` tag and besides, I don't think it's possible to easily have django-debug-toolbar work with jinja2 because it uses several internals of django's templating engine.

**Comment by strig** [comment]
@MoritzS you're right, I think I meant the `{% trans %}` tag actually. Anyways, I just figured out how to use the django template backend to render all the debug-toolbar templates instead.

**Comment by niwinz** [comment]
I'm currently using .jinja extension for my jinja templates that makes this task very easy. I'm currently using the debug-toolbar in serveral projects that uses django-jinja ;)

**Comment by MoritzS** [comment]
I mentioned django-jinja in the Readme.

I think, I can close this now.

**Comment by megahoy** [comment]
debug-toolbar fails with django-jinja - 'Environment' object has no attribute 'install_gettext_translations'
/usr/local/lib/python2.7/dist-packages/django_jinja/backend.py in __init__, line 142
