### ISSUE TITLE
Question about implementing Django-style tag

### ISSUE THREAD

**Issue by oTree-org** [MoritzS/jinja2-django-tags#12]
Hi! I am switching from Django templates to Jinja and trying to write my own Extensions, by studying your code in extensions.py. Thank you for providing this guide.

I have a tag that takes 1 required positional arg and 1 optional kwarg:

```
{% form_field 'age' label='how old are you?' %}.
```

I know that in Jinja this should be a macro like `{% form_field('age', label='how old are you?') %}`, but for compatibility I need to preserve the old Django-style syntax.

I am wondering about the simplest way to implement this? Because this template tag is just like a python function with 2 args (no special syntax or custom keywords like `with`, `as`, etc).

Or do I need to parse the tokens one by one, check if each is TOKEN_STRING, TOKEN_NAME, etc.? Although I read your code, I am not sure how to deal with the case where the args are context variables, e.g.:

```
context = {'field_name': 'age', 'label': 'How old are you?'}
```

`{% form_field field_name label=label %}`.

Any advice? Thank you so much.

**Comment by MoritzS** [comment]
Yes, as you can see in the code, you need to go through the token list and parse all information you need from it. Then you need to create a jinja2 node that jinja2 will use to generate the output of the template.
