### ISSUE TITLE
{% blcktrans %} not working with plural forms

### ISSUE THREAD

**Issue by syenchuk** [MoritzS/jinja2-django-tags#4]
Template:

``` jinja
{% blocktrans count candy_num=4 %}
  {{ candy_num }} candy
{% plural %}
  {{ candy_num }} candies
{% endblocktrans %}
```

Result:

`'candy_num' is undefined`

In `extensions.py`, things seem to get wrong at [line 266](https://github.com/MoritzS/jinja2-django-tags/blob/master/jdj_tags/extensions.py#L266):

``` python
            if context is None:
                return ugettext(force_text(singular)) % trans_vars
            else:
                return pgettext(force_text(context), force_text(singular)) % trans_vars
        else:
            if context is None:
                return ungettext(
                    force_text(singular), force_text(plural), trans_vars[count_var] # errorneous
                ) % trans_vars
            else:
                return npgettext(
                    force_text(context), force_text(singular), force_text(plural),
                    trans_vars[count_var]
                ) % trans_vars

```

Local vars:

| Variable | Value |
| --- | --- |
| context | `None` |
| count_var | `'candy_num'` |
| plural | `Markup('\n  %(candy_num)s candies\n')` |
| self | `<jdj_tags.extensions.DjangoCompat object at 0x…>` |
| singular | `Markup('\n  %(candy_num)s candy\n')` |
| trans_vars | `{'candy_num': Undefined}` |

**Comment by alexpirine** [comment]
The main issue was with wrongly constructed `kwargs`:

```
[
    Keyword(
        key='trans_vars',
        value=Dict(
            items=[
                Pair(key=Const(value='candy_num'), value=Const(value=4)),
                Pair(key=Const(value='candy_num'), value=Name(name='candy_num', ctx='load'))
            ])
    ),
    Keyword(key='count_var', value=Const(value='candy_num'))
]
```

Notice how `trans_vars` has two values, the last one coming from `additional_vars` and resulting in the UndefinedError. This was fixed by adding the counter name to `with_vars`.

`int(trans_vars[count_var])` was necessary because `trans_vars[count_var]` is SafeText, thus resulting in the `TypeError: unorderable types: SafeText() > int()` error in the gettext module.

**Comment by MoritzS** [comment]
There is no need to open both an issue and a pull request, the pr is sufficient.

**Comment by syenchuk** [comment]
Sorry, but I discovered the issue first and didn't think I would fix it.
