### ISSUE TITLE
Localizing dates in templates

### ISSUE THREAD

**Issue by M1ha-Shvn** [MoritzS/jinja2-django-tags#8]
Hi.
I'm not understanding, how date region dependent localization works. 
1) Is it like django `{{ date|localize }}` ? I always get isoformat now, my FORMAT_MODULE_PATH is ignored, 
2) If I want to get localized date, what should I activate? translation.activate('ru')? or timezone.activate(...) or both? 
Thanks

**Comment by MoritzS** [comment]
This library currently only respects the `USE_TZ` and `USE_L10N` settings as documented in the Django docs. The `localize` filter and tags are not implemented.
